// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: example.proto
#ifndef GRPC_example_2eproto__INCLUDED
#define GRPC_example_2eproto__INCLUDED

#include "example.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace posetrl {

class PosetRL final {
 public:
  static constexpr char const* service_full_name() {
    return "posetrl.PosetRL";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status getEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::posetrl::EmbeddingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>> AsyncgetEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>>(AsyncgetEmbeddingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>> PrepareAsyncgetEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>>(PrepareAsyncgetEmbeddingRaw(context, request, cq));
    }
    virtual ::grpc::Status applyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncapplyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncapplyActionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncapplyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncapplyActionRaw(context, request, cq));
    }
    virtual ::grpc::Status applyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::posetrl::EmbeddingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>> AsyncapplyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>>(AsyncapplyActionGetEmbeddingsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>> PrepareAsyncapplyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>>(PrepareAsyncapplyActionGetEmbeddingsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void getEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::posetrl::EmbeddingResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::posetrl::EmbeddingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::posetrl::EmbeddingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void applyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void applyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void applyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::google::protobuf::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void applyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::posetrl::EmbeddingResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void applyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::posetrl::EmbeddingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void applyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::posetrl::EmbeddingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>* AsyncgetEmbeddingRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>* PrepareAsyncgetEmbeddingRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncapplyActionRaw(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncapplyActionRaw(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>* AsyncapplyActionGetEmbeddingsRaw(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::posetrl::EmbeddingResponse>* PrepareAsyncapplyActionGetEmbeddingsRaw(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status getEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::posetrl::EmbeddingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>> AsyncgetEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>>(AsyncgetEmbeddingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>> PrepareAsyncgetEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>>(PrepareAsyncgetEmbeddingRaw(context, request, cq));
    }
    ::grpc::Status applyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncapplyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncapplyActionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncapplyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncapplyActionRaw(context, request, cq));
    }
    ::grpc::Status applyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::posetrl::EmbeddingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>> AsyncapplyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>>(AsyncapplyActionGetEmbeddingsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>> PrepareAsyncapplyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>>(PrepareAsyncapplyActionGetEmbeddingsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void getEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::posetrl::EmbeddingResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::posetrl::EmbeddingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getEmbedding(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::posetrl::EmbeddingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void applyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void applyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void applyAction(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::google::protobuf::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void applyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::posetrl::EmbeddingResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void applyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::posetrl::EmbeddingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void applyActionGetEmbeddings(::grpc::ClientContext* context, const ::posetrl::ActionRequest* request, ::posetrl::EmbeddingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>* AsyncgetEmbeddingRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>* PrepareAsyncgetEmbeddingRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncapplyActionRaw(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncapplyActionRaw(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>* AsyncapplyActionGetEmbeddingsRaw(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::posetrl::EmbeddingResponse>* PrepareAsyncapplyActionGetEmbeddingsRaw(::grpc::ClientContext* context, const ::posetrl::ActionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getEmbedding_;
    const ::grpc::internal::RpcMethod rpcmethod_applyAction_;
    const ::grpc::internal::RpcMethod rpcmethod_applyActionGetEmbeddings_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status getEmbedding(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::posetrl::EmbeddingResponse* response);
    virtual ::grpc::Status applyAction(::grpc::ServerContext* context, const ::posetrl::ActionRequest* request, ::google::protobuf::Empty* response);
    virtual ::grpc::Status applyActionGetEmbeddings(::grpc::ServerContext* context, const ::posetrl::ActionRequest* request, ::posetrl::EmbeddingResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getEmbedding() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getEmbedding(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetEmbedding(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::posetrl::EmbeddingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_applyAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_applyAction() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_applyAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyAction(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestapplyAction(::grpc::ServerContext* context, ::posetrl::ActionRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_applyActionGetEmbeddings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_applyActionGetEmbeddings() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_applyActionGetEmbeddings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyActionGetEmbeddings(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestapplyActionGetEmbeddings(::grpc::ServerContext* context, ::posetrl::ActionRequest* request, ::grpc::ServerAsyncResponseWriter< ::posetrl::EmbeddingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getEmbedding<WithAsyncMethod_applyAction<WithAsyncMethod_applyActionGetEmbeddings<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_getEmbedding() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::posetrl::EmbeddingResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::google::protobuf::Empty* request, ::posetrl::EmbeddingResponse* response) { return this->getEmbedding(context, request, response); }));}
    void SetMessageAllocatorFor_getEmbedding(
        ::grpc::experimental::MessageAllocator< ::google::protobuf::Empty, ::posetrl::EmbeddingResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::posetrl::EmbeddingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_getEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getEmbedding(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getEmbedding(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::posetrl::EmbeddingResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getEmbedding(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::posetrl::EmbeddingResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_applyAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_applyAction() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::posetrl::ActionRequest, ::google::protobuf::Empty>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::posetrl::ActionRequest* request, ::google::protobuf::Empty* response) { return this->applyAction(context, request, response); }));}
    void SetMessageAllocatorFor_applyAction(
        ::grpc::experimental::MessageAllocator< ::posetrl::ActionRequest, ::google::protobuf::Empty>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::posetrl::ActionRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_applyAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyAction(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* applyAction(
      ::grpc::CallbackServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::google::protobuf::Empty* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* applyAction(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::google::protobuf::Empty* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_applyActionGetEmbeddings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_applyActionGetEmbeddings() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::posetrl::ActionRequest, ::posetrl::EmbeddingResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::posetrl::ActionRequest* request, ::posetrl::EmbeddingResponse* response) { return this->applyActionGetEmbeddings(context, request, response); }));}
    void SetMessageAllocatorFor_applyActionGetEmbeddings(
        ::grpc::experimental::MessageAllocator< ::posetrl::ActionRequest, ::posetrl::EmbeddingResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::posetrl::ActionRequest, ::posetrl::EmbeddingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_applyActionGetEmbeddings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyActionGetEmbeddings(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* applyActionGetEmbeddings(
      ::grpc::CallbackServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::posetrl::EmbeddingResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* applyActionGetEmbeddings(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::posetrl::EmbeddingResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_getEmbedding<ExperimentalWithCallbackMethod_applyAction<ExperimentalWithCallbackMethod_applyActionGetEmbeddings<Service > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_getEmbedding<ExperimentalWithCallbackMethod_applyAction<ExperimentalWithCallbackMethod_applyActionGetEmbeddings<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getEmbedding() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getEmbedding(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_applyAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_applyAction() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_applyAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyAction(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_applyActionGetEmbeddings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_applyActionGetEmbeddings() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_applyActionGetEmbeddings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyActionGetEmbeddings(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getEmbedding() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getEmbedding(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetEmbedding(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_applyAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_applyAction() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_applyAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyAction(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestapplyAction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_applyActionGetEmbeddings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_applyActionGetEmbeddings() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_applyActionGetEmbeddings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyActionGetEmbeddings(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestapplyActionGetEmbeddings(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_getEmbedding() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getEmbedding(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_getEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getEmbedding(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getEmbedding(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getEmbedding(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_applyAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_applyAction() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->applyAction(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_applyAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyAction(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* applyAction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* applyAction(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_applyActionGetEmbeddings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_applyActionGetEmbeddings() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->applyActionGetEmbeddings(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_applyActionGetEmbeddings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applyActionGetEmbeddings(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* applyActionGetEmbeddings(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* applyActionGetEmbeddings(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getEmbedding() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::posetrl::EmbeddingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::posetrl::EmbeddingResponse>* streamer) {
                       return this->StreamedgetEmbedding(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getEmbedding(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetEmbedding(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::posetrl::EmbeddingResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_applyAction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_applyAction() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::posetrl::ActionRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::posetrl::ActionRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedapplyAction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_applyAction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status applyAction(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedapplyAction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::posetrl::ActionRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_applyActionGetEmbeddings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_applyActionGetEmbeddings() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::posetrl::ActionRequest, ::posetrl::EmbeddingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::posetrl::ActionRequest, ::posetrl::EmbeddingResponse>* streamer) {
                       return this->StreamedapplyActionGetEmbeddings(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_applyActionGetEmbeddings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status applyActionGetEmbeddings(::grpc::ServerContext* /*context*/, const ::posetrl::ActionRequest* /*request*/, ::posetrl::EmbeddingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedapplyActionGetEmbeddings(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::posetrl::ActionRequest,::posetrl::EmbeddingResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getEmbedding<WithStreamedUnaryMethod_applyAction<WithStreamedUnaryMethod_applyActionGetEmbeddings<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getEmbedding<WithStreamedUnaryMethod_applyAction<WithStreamedUnaryMethod_applyActionGetEmbeddings<Service > > > StreamedService;
};

}  // namespace posetrl


#endif  // GRPC_example_2eproto__INCLUDED
