// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#include "example.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace posetrl {
PROTOBUF_CONSTEXPR EmbeddingResponse::EmbeddingResponse(
    ::_pbi::ConstantInitialized)
  : embedding_(){}
struct EmbeddingResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmbeddingResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmbeddingResponseDefaultTypeInternal() {}
  union {
    EmbeddingResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmbeddingResponseDefaultTypeInternal _EmbeddingResponse_default_instance_;
PROTOBUF_CONSTEXPR ActionRequest::ActionRequest(
    ::_pbi::ConstantInitialized)
  : action_(0){}
struct ActionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActionRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActionRequestDefaultTypeInternal() {}
  union {
    ActionRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActionRequestDefaultTypeInternal _ActionRequest_default_instance_;
}  // namespace posetrl
static ::_pb::Metadata file_level_metadata_example_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_example_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_example_2eproto = nullptr;

const uint32_t TableStruct_example_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::posetrl::EmbeddingResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::posetrl::EmbeddingResponse, embedding_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::posetrl::ActionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::posetrl::ActionRequest, action_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::posetrl::EmbeddingResponse)},
  { 7, -1, -1, sizeof(::posetrl::ActionRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::posetrl::_EmbeddingResponse_default_instance_._instance,
  &::posetrl::_ActionRequest_default_instance_._instance,
};

const char descriptor_table_protodef_example_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rexample.proto\022\007posetrl\032\033google/protobu"
  "f/empty.proto\"&\n\021EmbeddingResponse\022\021\n\tem"
  "bedding\030\001 \003(\002\"\037\n\rActionRequest\022\016\n\006action"
  "\030\001 \001(\0052\342\001\n\007PosetRL\022D\n\014getEmbedding\022\026.goo"
  "gle.protobuf.Empty\032\032.posetrl.EmbeddingRe"
  "sponse\"\000\022\?\n\013applyAction\022\026.posetrl.Action"
  "Request\032\026.google.protobuf.Empty\"\000\022P\n\030app"
  "lyActionGetEmbeddings\022\026.posetrl.ActionRe"
  "quest\032\032.posetrl.EmbeddingResponse\"\000b\006pro"
  "to3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_example_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::_pbi::once_flag descriptor_table_example_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_example_2eproto = {
    false, false, 363, descriptor_table_protodef_example_2eproto,
    "example.proto",
    &descriptor_table_example_2eproto_once, descriptor_table_example_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_example_2eproto::offsets,
    file_level_metadata_example_2eproto, file_level_enum_descriptors_example_2eproto,
    file_level_service_descriptors_example_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_example_2eproto_getter() {
  return &descriptor_table_example_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_example_2eproto(&descriptor_table_example_2eproto);
namespace posetrl {

// ===================================================================

class EmbeddingResponse::_Internal {
 public:
};

EmbeddingResponse::EmbeddingResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  embedding_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:posetrl.EmbeddingResponse)
}
EmbeddingResponse::EmbeddingResponse(const EmbeddingResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      embedding_(from.embedding_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:posetrl.EmbeddingResponse)
}

inline void EmbeddingResponse::SharedCtor() {
}

EmbeddingResponse::~EmbeddingResponse() {
  // @@protoc_insertion_point(destructor:posetrl.EmbeddingResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EmbeddingResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void EmbeddingResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void EmbeddingResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:posetrl.EmbeddingResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  embedding_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EmbeddingResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float embedding = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_embedding(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 13) {
          _internal_add_embedding(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EmbeddingResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:posetrl.EmbeddingResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float embedding = 1;
  if (this->_internal_embedding_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_embedding(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:posetrl.EmbeddingResponse)
  return target;
}

size_t EmbeddingResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:posetrl.EmbeddingResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float embedding = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_embedding_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EmbeddingResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    EmbeddingResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EmbeddingResponse::GetClassData() const { return &_class_data_; }

void EmbeddingResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<EmbeddingResponse *>(to)->MergeFrom(
      static_cast<const EmbeddingResponse &>(from));
}


void EmbeddingResponse::MergeFrom(const EmbeddingResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:posetrl.EmbeddingResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  embedding_.MergeFrom(from.embedding_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EmbeddingResponse::CopyFrom(const EmbeddingResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:posetrl.EmbeddingResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EmbeddingResponse::IsInitialized() const {
  return true;
}

void EmbeddingResponse::InternalSwap(EmbeddingResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  embedding_.InternalSwap(&other->embedding_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EmbeddingResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_example_2eproto_getter, &descriptor_table_example_2eproto_once,
      file_level_metadata_example_2eproto[0]);
}

// ===================================================================

class ActionRequest::_Internal {
 public:
};

ActionRequest::ActionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:posetrl.ActionRequest)
}
ActionRequest::ActionRequest(const ActionRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  action_ = from.action_;
  // @@protoc_insertion_point(copy_constructor:posetrl.ActionRequest)
}

inline void ActionRequest::SharedCtor() {
action_ = 0;
}

ActionRequest::~ActionRequest() {
  // @@protoc_insertion_point(destructor:posetrl.ActionRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActionRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ActionRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ActionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:posetrl.ActionRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  action_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActionRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 action = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          action_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActionRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:posetrl.ActionRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 action = 1;
  if (this->_internal_action() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_action(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:posetrl.ActionRequest)
  return target;
}

size_t ActionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:posetrl.ActionRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 action = 1;
  if (this->_internal_action() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_action());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActionRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ActionRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActionRequest::GetClassData() const { return &_class_data_; }

void ActionRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ActionRequest *>(to)->MergeFrom(
      static_cast<const ActionRequest &>(from));
}


void ActionRequest::MergeFrom(const ActionRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:posetrl.ActionRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_action() != 0) {
    _internal_set_action(from._internal_action());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActionRequest::CopyFrom(const ActionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:posetrl.ActionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionRequest::IsInitialized() const {
  return true;
}

void ActionRequest::InternalSwap(ActionRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(action_, other->action_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_example_2eproto_getter, &descriptor_table_example_2eproto_once,
      file_level_metadata_example_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace posetrl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::posetrl::EmbeddingResponse*
Arena::CreateMaybeMessage< ::posetrl::EmbeddingResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::posetrl::EmbeddingResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::posetrl::ActionRequest*
Arena::CreateMaybeMessage< ::posetrl::ActionRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::posetrl::ActionRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
