# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07posetrl\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"\x1f\n\rActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32\xe2\x01\n\x07PosetRL\x12\x44\n\x0cgetEmbedding\x12\x16.google.protobuf.Empty\x1a\x1a.posetrl.EmbeddingResponse\"\x00\x12?\n\x0b\x61pplyAction\x12\x16.posetrl.ActionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12P\n\x18\x61pplyActionGetEmbeddings\x12\x16.posetrl.ActionRequest\x1a\x1a.posetrl.EmbeddingResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMBEDDINGRESPONSE._serialized_start=55
  _EMBEDDINGRESPONSE._serialized_end=93
  _ACTIONREQUEST._serialized_start=95
  _ACTIONREQUEST._serialized_end=126
  _POSETRL._serialized_start=129
  _POSETRL._serialized_end=355
# @@protoc_insertion_point(module_scope)
