// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RegisterAllocationInference.proto

#include "RegisterAllocationInference.pb.h"
#include "RegisterAllocationInference.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace registerallocationinference {

static const char* RegisterAllocationInference_method_names[] = {
  "/registerallocationinference.RegisterAllocationInference/getColouring",
};

std::unique_ptr< RegisterAllocationInference::Stub> RegisterAllocationInference::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RegisterAllocationInference::Stub> stub(new RegisterAllocationInference::Stub(channel));
  return stub;
}

RegisterAllocationInference::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_getColouring_(RegisterAllocationInference_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RegisterAllocationInference::Stub::getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::registerallocationinference::ColorData* response) {
  return ::grpc::internal::BlockingUnaryCall< ::registerallocationinference::GraphList, ::registerallocationinference::ColorData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getColouring_, context, request, response);
}

void RegisterAllocationInference::Stub::experimental_async::getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::registerallocationinference::GraphList, ::registerallocationinference::ColorData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getColouring_, context, request, response, std::move(f));
}

void RegisterAllocationInference::Stub::experimental_async::getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getColouring_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::registerallocationinference::ColorData>* RegisterAllocationInference::Stub::PrepareAsyncgetColouringRaw(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::registerallocationinference::ColorData, ::registerallocationinference::GraphList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getColouring_, context, request);
}

::grpc::ClientAsyncResponseReader< ::registerallocationinference::ColorData>* RegisterAllocationInference::Stub::AsyncgetColouringRaw(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetColouringRaw(context, request, cq);
  result->StartCall();
  return result;
}

RegisterAllocationInference::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RegisterAllocationInference_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RegisterAllocationInference::Service, ::registerallocationinference::GraphList, ::registerallocationinference::ColorData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RegisterAllocationInference::Service* service,
             ::grpc::ServerContext* ctx,
             const ::registerallocationinference::GraphList* req,
             ::registerallocationinference::ColorData* resp) {
               return service->getColouring(ctx, req, resp);
             }, this)));
}

RegisterAllocationInference::Service::~Service() {
}

::grpc::Status RegisterAllocationInference::Service::getColouring(::grpc::ServerContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace registerallocationinference

