// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RegisterAllocationInference.proto
#ifndef GRPC_RegisterAllocationInference_2eproto__INCLUDED
#define GRPC_RegisterAllocationInference_2eproto__INCLUDED

#include "RegisterAllocationInference.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace registerallocationinference {

// General Register Allocation Service 
class RegisterAllocationInference final {
 public:
  static constexpr char const* service_full_name() {
    return "registerallocationinference.RegisterAllocationInference";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // RPC function to send Inference graph data and receive color data for codegen
    virtual ::grpc::Status getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::registerallocationinference::ColorData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::registerallocationinference::ColorData>> AsyncgetColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::registerallocationinference::ColorData>>(AsyncgetColouringRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::registerallocationinference::ColorData>> PrepareAsyncgetColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::registerallocationinference::ColorData>>(PrepareAsyncgetColouringRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // RPC function to send Inference graph data and receive color data for codegen
      virtual void getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::registerallocationinference::ColorData>* AsyncgetColouringRaw(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::registerallocationinference::ColorData>* PrepareAsyncgetColouringRaw(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::registerallocationinference::ColorData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::registerallocationinference::ColorData>> AsyncgetColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::registerallocationinference::ColorData>>(AsyncgetColouringRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::registerallocationinference::ColorData>> PrepareAsyncgetColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::registerallocationinference::ColorData>>(PrepareAsyncgetColouringRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getColouring(::grpc::ClientContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::registerallocationinference::ColorData>* AsyncgetColouringRaw(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::registerallocationinference::ColorData>* PrepareAsyncgetColouringRaw(::grpc::ClientContext* context, const ::registerallocationinference::GraphList& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getColouring_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // RPC function to send Inference graph data and receive color data for codegen
    virtual ::grpc::Status getColouring(::grpc::ServerContext* context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getColouring : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getColouring() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getColouring() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getColouring(::grpc::ServerContext* /*context*/, const ::registerallocationinference::GraphList* /*request*/, ::registerallocationinference::ColorData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetColouring(::grpc::ServerContext* context, ::registerallocationinference::GraphList* request, ::grpc::ServerAsyncResponseWriter< ::registerallocationinference::ColorData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getColouring<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getColouring : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_getColouring() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::registerallocationinference::GraphList, ::registerallocationinference::ColorData>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::registerallocationinference::GraphList* request, ::registerallocationinference::ColorData* response) { return this->getColouring(context, request, response); }));}
    void SetMessageAllocatorFor_getColouring(
        ::grpc::experimental::MessageAllocator< ::registerallocationinference::GraphList, ::registerallocationinference::ColorData>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::registerallocationinference::GraphList, ::registerallocationinference::ColorData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_getColouring() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getColouring(::grpc::ServerContext* /*context*/, const ::registerallocationinference::GraphList* /*request*/, ::registerallocationinference::ColorData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getColouring(
      ::grpc::CallbackServerContext* /*context*/, const ::registerallocationinference::GraphList* /*request*/, ::registerallocationinference::ColorData* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getColouring(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::registerallocationinference::GraphList* /*request*/, ::registerallocationinference::ColorData* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_getColouring<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_getColouring<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getColouring : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getColouring() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getColouring() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getColouring(::grpc::ServerContext* /*context*/, const ::registerallocationinference::GraphList* /*request*/, ::registerallocationinference::ColorData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getColouring : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getColouring() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getColouring() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getColouring(::grpc::ServerContext* /*context*/, const ::registerallocationinference::GraphList* /*request*/, ::registerallocationinference::ColorData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetColouring(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getColouring : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_getColouring() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getColouring(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_getColouring() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getColouring(::grpc::ServerContext* /*context*/, const ::registerallocationinference::GraphList* /*request*/, ::registerallocationinference::ColorData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getColouring(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getColouring(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getColouring : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getColouring() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::registerallocationinference::GraphList, ::registerallocationinference::ColorData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::registerallocationinference::GraphList, ::registerallocationinference::ColorData>* streamer) {
                       return this->StreamedgetColouring(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getColouring() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getColouring(::grpc::ServerContext* /*context*/, const ::registerallocationinference::GraphList* /*request*/, ::registerallocationinference::ColorData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetColouring(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::registerallocationinference::GraphList,::registerallocationinference::ColorData>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getColouring<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getColouring<Service > StreamedService;
};

}  // namespace registerallocationinference


#endif  // GRPC_RegisterAllocationInference_2eproto__INCLUDED
