# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import helloMLBridge_pb2 as helloMLBridge__pb2


class HelloMLBridgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTensor = channel.unary_unary(
                '/helloMLBridgegRPC.HelloMLBridgeService/getTensor',
                request_serializer=helloMLBridge__pb2.ActionRequest.SerializeToString,
                response_deserializer=helloMLBridge__pb2.TensorResponse.FromString,
                )
        self.getAdvice = channel.unary_unary(
                '/helloMLBridgegRPC.HelloMLBridgeService/getAdvice',
                request_serializer=helloMLBridge__pb2.TensorResponse.SerializeToString,
                response_deserializer=helloMLBridge__pb2.ActionRequest.FromString,
                )


class HelloMLBridgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAdvice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloMLBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.getTensor,
                    request_deserializer=helloMLBridge__pb2.ActionRequest.FromString,
                    response_serializer=helloMLBridge__pb2.TensorResponse.SerializeToString,
            ),
            'getAdvice': grpc.unary_unary_rpc_method_handler(
                    servicer.getAdvice,
                    request_deserializer=helloMLBridge__pb2.TensorResponse.FromString,
                    response_serializer=helloMLBridge__pb2.ActionRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloMLBridgegRPC.HelloMLBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HelloMLBridgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloMLBridgegRPC.HelloMLBridgeService/getTensor',
            helloMLBridge__pb2.ActionRequest.SerializeToString,
            helloMLBridge__pb2.TensorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAdvice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloMLBridgegRPC.HelloMLBridgeService/getAdvice',
            helloMLBridge__pb2.TensorResponse.SerializeToString,
            helloMLBridge__pb2.ActionRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
