# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloMLBridge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloMLBridge.proto',
  package='helloMLBridgegRPC',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13helloMLBridge.proto\x12\x11helloMLBridgegRPC\" \n\x0eTensorResponse\x12\x0e\n\x06tensor\x18\x01 \x03(\x02\"\x1f\n\rActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32\xbe\x01\n\x14HelloMLBridgeService\x12R\n\tgetTensor\x12 .helloMLBridgegRPC.ActionRequest\x1a!.helloMLBridgegRPC.TensorResponse\"\x00\x12R\n\tgetAdvice\x12!.helloMLBridgegRPC.TensorResponse\x1a .helloMLBridgegRPC.ActionRequest\"\x00\x62\x06proto3'
)




_TENSORRESPONSE = _descriptor.Descriptor(
  name='TensorResponse',
  full_name='helloMLBridgegRPC.TensorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor', full_name='helloMLBridgegRPC.TensorResponse.tensor', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=74,
)


_ACTIONREQUEST = _descriptor.Descriptor(
  name='ActionRequest',
  full_name='helloMLBridgegRPC.ActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='helloMLBridgegRPC.ActionRequest.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['TensorResponse'] = _TENSORRESPONSE
DESCRIPTOR.message_types_by_name['ActionRequest'] = _ACTIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TensorResponse = _reflection.GeneratedProtocolMessageType('TensorResponse', (_message.Message,), {
  'DESCRIPTOR' : _TENSORRESPONSE,
  '__module__' : 'helloMLBridge_pb2'
  # @@protoc_insertion_point(class_scope:helloMLBridgegRPC.TensorResponse)
  })
_sym_db.RegisterMessage(TensorResponse)

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONREQUEST,
  '__module__' : 'helloMLBridge_pb2'
  # @@protoc_insertion_point(class_scope:helloMLBridgegRPC.ActionRequest)
  })
_sym_db.RegisterMessage(ActionRequest)



_HELLOMLBRIDGESERVICE = _descriptor.ServiceDescriptor(
  name='HelloMLBridgeService',
  full_name='helloMLBridgegRPC.HelloMLBridgeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=300,
  methods=[
  _descriptor.MethodDescriptor(
    name='getTensor',
    full_name='helloMLBridgegRPC.HelloMLBridgeService.getTensor',
    index=0,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_TENSORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getAdvice',
    full_name='helloMLBridgegRPC.HelloMLBridgeService.getAdvice',
    index=1,
    containing_service=None,
    input_type=_TENSORRESPONSE,
    output_type=_ACTIONREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOMLBRIDGESERVICE)

DESCRIPTOR.services_by_name['HelloMLBridgeService'] = _HELLOMLBRIDGESERVICE

# @@protoc_insertion_point(module_scope)
