# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posetRL.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='posetRL.proto',
  package='posetRLgRPC',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rposetRL.proto\x12\x0bposetRLgRPC\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"\x1f\n\rActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32\x84\x02\n\x0ePosetRLService\x12X\n\x18\x61pplyActionGetEmbeddings\x12\x1a.posetRLgRPC.ActionRequest\x1a\x1e.posetRLgRPC.EmbeddingResponse\"\x00\x12M\n\rqueryCompiler\x12\x1a.posetRLgRPC.ActionRequest\x1a\x1e.posetRLgRPC.EmbeddingResponse\"\x00\x12I\n\tgetAdvice\x12\x1e.posetRLgRPC.EmbeddingResponse\x1a\x1a.posetRLgRPC.ActionRequest\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_EMBEDDINGRESPONSE = _descriptor.Descriptor(
  name='EmbeddingResponse',
  full_name='posetRLgRPC.EmbeddingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='embedding', full_name='posetRLgRPC.EmbeddingResponse.embedding', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=97,
)


_ACTIONREQUEST = _descriptor.Descriptor(
  name='ActionRequest',
  full_name='posetRLgRPC.ActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='posetRLgRPC.ActionRequest.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['EmbeddingResponse'] = _EMBEDDINGRESPONSE
DESCRIPTOR.message_types_by_name['ActionRequest'] = _ACTIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmbeddingResponse = _reflection.GeneratedProtocolMessageType('EmbeddingResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGRESPONSE,
  '__module__' : 'posetRL_pb2'
  # @@protoc_insertion_point(class_scope:posetRLgRPC.EmbeddingResponse)
  })
_sym_db.RegisterMessage(EmbeddingResponse)

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONREQUEST,
  '__module__' : 'posetRL_pb2'
  # @@protoc_insertion_point(class_scope:posetRLgRPC.ActionRequest)
  })
_sym_db.RegisterMessage(ActionRequest)



_POSETRLSERVICE = _descriptor.ServiceDescriptor(
  name='PosetRLService',
  full_name='posetRLgRPC.PosetRLService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=133,
  serialized_end=393,
  methods=[
  _descriptor.MethodDescriptor(
    name='applyActionGetEmbeddings',
    full_name='posetRLgRPC.PosetRLService.applyActionGetEmbeddings',
    index=0,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_EMBEDDINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='queryCompiler',
    full_name='posetRLgRPC.PosetRLService.queryCompiler',
    index=1,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_EMBEDDINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getAdvice',
    full_name='posetRLgRPC.PosetRLService.getAdvice',
    index=2,
    containing_service=None,
    input_type=_EMBEDDINGRESPONSE,
    output_type=_ACTIONREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSETRLSERVICE)

DESCRIPTOR.services_by_name['PosetRLService'] = _POSETRLSERVICE

# @@protoc_insertion_point(module_scope)
