# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoopDistribution.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LoopDistribution.proto',
  package='loopdistribution',
  syntax='proto3',
  serialized_options=b'\n!io.grpc.examples.loopdistributionB\025LoopDistributionProtoP\001\242\002\002LD',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16LoopDistribution.proto\x12\x10loopdistribution\"3\n\x17LoopDistributionRequest\x12\x18\n\x10partitionPattern\x18\x03 \x01(\t\"Q\n\x18LoopDistributionResponse\x12\x18\n\x10OrignialloopCost\x18\x01 \x01(\x03\x12\x1b\n\x13\x64istributedLoopCost\x18\x02 \x01(\x03\x32\x8b\x01\n\x10LoopDistribution\x12w\n\x1c\x64istributeLoopAndGetLoopCost\x12).loopdistribution.LoopDistributionRequest\x1a*.loopdistribution.LoopDistributionResponse\"\x00\x42\x41\n!io.grpc.examples.loopdistributionB\x15LoopDistributionProtoP\x01\xa2\x02\x02LDb\x06proto3'
)




_LOOPDISTRIBUTIONREQUEST = _descriptor.Descriptor(
  name='LoopDistributionRequest',
  full_name='loopdistribution.LoopDistributionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='partitionPattern', full_name='loopdistribution.LoopDistributionRequest.partitionPattern', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=95,
)


_LOOPDISTRIBUTIONRESPONSE = _descriptor.Descriptor(
  name='LoopDistributionResponse',
  full_name='loopdistribution.LoopDistributionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='OrignialloopCost', full_name='loopdistribution.LoopDistributionResponse.OrignialloopCost', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distributedLoopCost', full_name='loopdistribution.LoopDistributionResponse.distributedLoopCost', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['LoopDistributionRequest'] = _LOOPDISTRIBUTIONREQUEST
DESCRIPTOR.message_types_by_name['LoopDistributionResponse'] = _LOOPDISTRIBUTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoopDistributionRequest = _reflection.GeneratedProtocolMessageType('LoopDistributionRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOOPDISTRIBUTIONREQUEST,
  '__module__' : 'LoopDistribution_pb2'
  # @@protoc_insertion_point(class_scope:loopdistribution.LoopDistributionRequest)
  })
_sym_db.RegisterMessage(LoopDistributionRequest)

LoopDistributionResponse = _reflection.GeneratedProtocolMessageType('LoopDistributionResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOOPDISTRIBUTIONRESPONSE,
  '__module__' : 'LoopDistribution_pb2'
  # @@protoc_insertion_point(class_scope:loopdistribution.LoopDistributionResponse)
  })
_sym_db.RegisterMessage(LoopDistributionResponse)


DESCRIPTOR._options = None

_LOOPDISTRIBUTION = _descriptor.ServiceDescriptor(
  name='LoopDistribution',
  full_name='loopdistribution.LoopDistribution',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=181,
  serialized_end=320,
  methods=[
  _descriptor.MethodDescriptor(
    name='distributeLoopAndGetLoopCost',
    full_name='loopdistribution.LoopDistribution.distributeLoopAndGetLoopCost',
    index=0,
    containing_service=None,
    input_type=_LOOPDISTRIBUTIONREQUEST,
    output_type=_LOOPDISTRIBUTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOOPDISTRIBUTION)

DESCRIPTOR.services_by_name['LoopDistribution'] = _LOOPDISTRIBUTION

# @@protoc_insertion_point(module_scope)
