# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegisterAllocation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RegisterAllocation.proto',
  package='registerallocation',
  syntax='proto3',
  serialized_options=b'\n#io.grpc.examples.registerallocationB\027RegisterAllocationProtoP\001\242\002\003REG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18RegisterAllocation.proto\x12\x12registerallocation\"+\n\x04Path\x12\x0e\n\x06IRPath\x18\x01 \x01(\t\x12\x13\n\x0bSeedEmbPath\x18\x02 \x01(\t\"\x1c\n\tGraphList\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"5\n\x04\x44\x61ta\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03reg\x18\x02 \x01(\r\x12\x0f\n\x07payload\x18\x03 \x01(\x03\"\x07\n\x05\x45mpty2\xa2\x01\n\x12RegisterAllocation\x12\x46\n\tgetGraphs\x12\x18.registerallocation.Path\x1a\x1d.registerallocation.GraphList\"\x00\x12\x44\n\x07\x63odeGen\x12\x18.registerallocation.Data\x1a\x1d.registerallocation.GraphList\"\x00\x42\x46\n#io.grpc.examples.registerallocationB\x17RegisterAllocationProtoP\x01\xa2\x02\x03REGb\x06proto3'
)




_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='registerallocation.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='IRPath', full_name='registerallocation.Path.IRPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SeedEmbPath', full_name='registerallocation.Path.SeedEmbPath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=91,
)


_GRAPHLIST = _descriptor.Descriptor(
  name='GraphList',
  full_name='registerallocation.GraphList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='registerallocation.GraphList.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=121,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='registerallocation.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='registerallocation.Data.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reg', full_name='registerallocation.Data.reg', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='registerallocation.Data.payload', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=176,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='registerallocation.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['GraphList'] = _GRAPHLIST
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), {
  'DESCRIPTOR' : _PATH,
  '__module__' : 'RegisterAllocation_pb2'
  # @@protoc_insertion_point(class_scope:registerallocation.Path)
  })
_sym_db.RegisterMessage(Path)

GraphList = _reflection.GeneratedProtocolMessageType('GraphList', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHLIST,
  '__module__' : 'RegisterAllocation_pb2'
  # @@protoc_insertion_point(class_scope:registerallocation.GraphList)
  })
_sym_db.RegisterMessage(GraphList)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'RegisterAllocation_pb2'
  # @@protoc_insertion_point(class_scope:registerallocation.Data)
  })
_sym_db.RegisterMessage(Data)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'RegisterAllocation_pb2'
  # @@protoc_insertion_point(class_scope:registerallocation.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_REGISTERALLOCATION = _descriptor.ServiceDescriptor(
  name='RegisterAllocation',
  full_name='registerallocation.RegisterAllocation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=188,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='getGraphs',
    full_name='registerallocation.RegisterAllocation.getGraphs',
    index=0,
    containing_service=None,
    input_type=_PATH,
    output_type=_GRAPHLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='codeGen',
    full_name='registerallocation.RegisterAllocation.codeGen',
    index=1,
    containing_service=None,
    input_type=_DATA,
    output_type=_GRAPHLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTERALLOCATION)

DESCRIPTOR.services_by_name['RegisterAllocation'] = _REGISTERALLOCATION

# @@protoc_insertion_point(module_scope)
