# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegisterAllocationInference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RegisterAllocationInference.proto',
  package='registerallocationinference',
  syntax='proto3',
  serialized_options=b'\n,io.grpc.examples.registerallocationinferenceB RegisterAllocationInferenceProtoP\001\242\002\003REG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!RegisterAllocationInference.proto\x12\x1bregisterallocationinference\"\x1c\n\tGraphList\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x1c\n\tColorData\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x32\x7f\n\x1bRegisterAllocationInference\x12`\n\x0cgetColouring\x12&.registerallocationinference.GraphList\x1a&.registerallocationinference.ColorData\"\x00\x42X\n,io.grpc.examples.registerallocationinferenceB RegisterAllocationInferenceProtoP\x01\xa2\x02\x03REGb\x06proto3'
)




_GRAPHLIST = _descriptor.Descriptor(
  name='GraphList',
  full_name='registerallocationinference.GraphList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='registerallocationinference.GraphList.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=94,
)


_COLORDATA = _descriptor.Descriptor(
  name='ColorData',
  full_name='registerallocationinference.ColorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='registerallocationinference.ColorData.payload', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['GraphList'] = _GRAPHLIST
DESCRIPTOR.message_types_by_name['ColorData'] = _COLORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphList = _reflection.GeneratedProtocolMessageType('GraphList', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHLIST,
  '__module__' : 'RegisterAllocationInference_pb2'
  # @@protoc_insertion_point(class_scope:registerallocationinference.GraphList)
  })
_sym_db.RegisterMessage(GraphList)

ColorData = _reflection.GeneratedProtocolMessageType('ColorData', (_message.Message,), {
  'DESCRIPTOR' : _COLORDATA,
  '__module__' : 'RegisterAllocationInference_pb2'
  # @@protoc_insertion_point(class_scope:registerallocationinference.ColorData)
  })
_sym_db.RegisterMessage(ColorData)


DESCRIPTOR._options = None

_REGISTERALLOCATIONINFERENCE = _descriptor.ServiceDescriptor(
  name='RegisterAllocationInference',
  full_name='registerallocationinference.RegisterAllocationInference',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=126,
  serialized_end=253,
  methods=[
  _descriptor.MethodDescriptor(
    name='getColouring',
    full_name='registerallocationinference.RegisterAllocationInference.getColouring',
    index=0,
    containing_service=None,
    input_type=_GRAPHLIST,
    output_type=_COLORDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTERALLOCATIONINFERENCE)

DESCRIPTOR.services_by_name['RegisterAllocationInference'] = _REGISTERALLOCATIONINFERENCE

# @@protoc_insertion_point(module_scope)
